{
 "title": "ArgoCD / Application Operations",
 "description": "A dashboard that monitors ArgoCD with a focus on application operations. It is created using the [argo-cd-mixin](https://github.com/adinhodovic/argo-cd-mixin).",
 "tags": [
  "argo-cd",
  "gitops"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(argocd_app_info, namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(argocd_app_info{namespace=~\"$namespace\"}, dest_server)"
    }
   },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(argocd_app_info{namespace=~\"$namespace\", dest_server=~\"$cluster\"}, project)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Applications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(argocd_app_info{namespace=~\"$namespace\", dest_server=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Synced",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(argocd_app_info{namespace=~\"$namespace\", dest_server=~\"$cluster\", sync_status=\"Synced\"})"
    }
   ]
  },
  {
   "title": "Out of Sync",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(argocd_app_info{namespace=~\"$namespace\", dest_server=~\"$cluster\", sync_status=\"OutOfSync\"})"
    }
   ]
  },
  {
   "title": "Healthy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(argocd_app_info{namespace=~\"$namespace\", dest_server=~\"$cluster\", health_status=\"Healthy\"})"
    }
   ]
  },
  {
   "title": "Degraded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(argocd_app_info{namespace=~\"$namespace\", dest_server=~\"$cluster\", health_status=~\"Degraded|Missing\"})"
    }
   ]
  },
  { "title": "Application Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Applications",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "argocd_app_info{namespace=~\"$namespace\", dest_server=~\"$cluster\", project=~\"$project\"}"
    }
   ]
  },
  { "title": "Sync Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Sync Activity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "round(increase(argocd_app_sync_total{namespace=~\"$namespace\", dest_server=~\"$cluster\", project=~\"$project\"}[10m]))",
     "legendFormat": "{{dest_server}} - {{project}}/{{name}}"
    }
   ]
  },
  {
   "title": "Reconciliation Performance (p95)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(argocd_app_reconcile_bucket{namespace=~\"$namespace\", dest_server=~\"$cluster\", project=~\"$project\"}[5m])) by (le, dest_server, namespace, project, name))",
     "legendFormat": "{{dest_server}} - {{project}}/{{name}}"
    }
   ]
  },
  { "title": "Controller Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Controller Work Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(workqueue_depth{namespace=~\"$namespace\", name=~\"app_reconciliation_queue\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Controller Work Queue Adds Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{namespace=~\"$namespace\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}