apiVersion: v1
kind: Secret
metadata:
    name: adguard-credentials
    namespace: adguard
type: Opaque
data:
    password: ENC[AES256_GCM,data:CnFxJ0gDmG09cIKj,iv:CDL8kEy/skYty2Y5Qb0RzlJ1luJuTgocB5kbb6Sucbw=,tag:xFM0AUCkuf9/MmP0IxQGIA==,type:str]
    username: ENC[AES256_GCM,data:86y0s/J0Diw+vCL5,iv:s3jt6b1wH5eFTInY4dGCsYo8DiYWAm2i2L8Cfwmvsqs=,tag:H+DxKiDzQC0eTT4AQdQ+mg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcFZLTVdWVDdNeGxDc2VC
            OUFiSEd2RHF2WmxzRXdYN0JqaGovaTB6T2tJClJqNkFMM29nSEdoNjRoc0VvSWtP
            MGhGY1lCUlk4TFVPL2pWdTA3cjkyVE0KLS0tIEVQd3c2Y1lSR21vY1A3ZU1IclpI
            SlFjZ0tYYW4rYkpySTFiQ01mYkE2UWcKTHFMcGCjgVP+HPZxkLCwwOeenvLK+y7Z
            1Qo64f2loAuPIKQPmWbIrH6K4RLYVVxnPBBA0ldzuEHw7R7KS6Q2Lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16jjl5fju6syvlmqryqnscc80ertz87fydjf8dxfuhm77ycuw0clqwuyn85
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T13:08:38Z"
    mac: ENC[AES256_GCM,data:zPkoq8tsmTHnz9tMolbQB3qF3OCYA/zNt8jqgUxIAu6nmtAmqWzISMOwfmCg1aVlLzkZ1/21qa2Eq8/SnU/jOoimtEVfRxkR4/64JCqJaAaE7lco2VoqlPWUGM6XjnKlaYvPhVQot2LeQT//GQAOSZJ0yy++3Zt5DX3qnl1TJyA=,iv:Z6hvUgG7phqX4L99zUR/aBTYadwTPcxJlCTRDwb+m8M=,tag:n1T4sMWH35Tlq5STKkA6GQ==,type:str]
    version: 3.13.3
