apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-exporter
  namespace: adguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard-exporter
  template:
    metadata:
      labels:
        app: adguard-exporter
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: adguard-exporter
          image: ghcr.io/henrywhitaker3/adguard-exporter:v1.2.1
          ports:
            - containerPort: 9618
              name: metrics
          env:
            - name: ADGUARD_SERVERS
              value: "http://adguard-home.adguard.svc.cluster.local:80"
            - name: ADGUARD_USERNAMES
              valueFrom:
                secretKeyRef:
                  name: adguard-credentials
                  key: username
            - name: ADGUARD_PASSWORDS
              valueFrom:
                secretKeyRef:
                  name: adguard-credentials
                  key: password
            - name: INTERVAL
              value: "30s"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              memory: 32Mi
              cpu: 10m
            limits:
              memory: 64Mi
              cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-exporter
  namespace: adguard
  labels:
    app: adguard-exporter
spec:
  type: ClusterIP
  selector:
    app: adguard-exporter
  ports:
    - port: 9618
      targetPort: 9618
      protocol: TCP
      name: metrics
