apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - adguard-home.yaml
  - adguard-exporter.yaml
  - adguard-route.yaml
  - adguard-servicemonitor.yaml
generators:
  - ksops-generator.yaml
