apiVersion: v1
kind: Secret
metadata:
    name: adguard-credentials
    namespace: external-dns
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:o3nB0icAcKk=,iv:1yMbtF/MhUpB/4rxEDjklbJW4p+0Gyil+iEMmyCqCfw=,tag:yzHAcOSOo5u3dic0MYbObg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZ3ZFZGFreHVLREdDU0kr
            Q1VCMWNmZEo4Y1pDeEpzd002eVYvckFPVWpnCnBWZ1dlYTJWblBWbHN1U0E1aERl
            bDNVdW9HZWNsdVhwWGEyWDYrOE9TY2cKLS0tIEtkNEZRejhWY1ZqU2hTNVNQTTlk
            RWs3NE1KT3VxNGwrZzJVWTcyZ2NxVzQKGcqIkCs/kt7Y+ZnEOJlHgyRrR1z8+Xpw
            sU8j7+b9kWoilrFcxQvBpiw4nvmxFC5CD2m7yivPgOQRUuWQVyw/+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16jjl5fju6syvlmqryqnscc80ertz87fydjf8dxfuhm77ycuw0clqwuyn85
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T12:23:13Z"
    mac: ENC[AES256_GCM,data:zOslOykD36eXkL52cdvjET+7W+TCxaPkVso/s2+0gY7TS8jqdNvXCIRoNWUdEHI3nHYlKJnD2reHLsGwt2vT2q/WDkQO8Cf4nnnuy5ndLTMdoqzQ3alP40y4ZaKSb7TrlHEsFvsm2PKd+E8CRiSh5gEi+kFzeB80edR2Qy+NQ4Y=,iv:IklqSH5I30/DZXSbrGBh6hLh6lmicak5qaXxCcN4c2I=,tag:BNa6ss92KNyOdvUTIelgOw==,type:str]
    version: 3.13.3
