apiVersion: v1
kind: Secret
metadata:
    name: adguard-credentials
    namespace: external-dns
type: Opaque
data:
    password: ENC[AES256_GCM,data:tn1BzaYTLIVmIDW8,iv:Yxr0Z23PxPzI6n8ZWvlFN45keSc8otTj2RHQgft2Gww=,tag:ycOXXtTXPJVdGPiNlUilpA==,type:str]
    username: ENC[AES256_GCM,data:xQskpEU/5Greo++X,iv:WAotZmfuVv0Hyw85DrvetQs1C8L7RIf+prHkwcrEUY8=,tag:HlNyLKzL1iksbUNwmhwY6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicmp3c1E5cEppQ1RxYUky
            c09pRkxTc3NzNU93OFc1L3JLc3lWSnhYYXlZCk00TmVSQW9DYlN6ei9HbExFbUlP
            K0NFS0RjTkpyTXJ3SENoZXpJeDdtQmcKLS0tIFZHMklOdWp3R01uUUxOZ3luWGhO
            MnJ4K21jL05vUDZrOEpNUU12NnBDRDAKGfbTIqUQw0hPR/mRMBGm731Z5A11IRVE
            cm6tykuOCcfQ2roZ1eVEsuXja00m/kDu0tAPRdh+2sfjlKblG+2Few==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16jjl5fju6syvlmqryqnscc80ertz87fydjf8dxfuhm77ycuw0clqwuyn85
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T13:04:02Z"
    mac: ENC[AES256_GCM,data:gWwva3Fk1U6Vb+0vXM/hs6LA/QCmvjsGq7JwIpWBKx8+qCkKjOLlXECsI8kqC2vlr+AyPgZ2epbmESzeWJ3+Pb74d56kQ8wv74jnsv33uRh1m4L1zaF2QqDww54R/wGXtVHx+S7qTxXdA9epsDcudDuSR6Eq3t6k+1CHGnBZO8o=,iv:RqejoZDdNDQ2u3tDsU0KyROMl5Y0d1VdUOo+sJqfPJo=,tag:NA//pIWcBnyIWY7dh4ijHA==,type:str]
    version: 3.13.3
