apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lifting-data-db
  namespace: lifting-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lifting-data-output
  namespace: lifting-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
